- name: MIGRACION - Subir archivos x
  hosts: all
  tasks:    
    - name: Copy Remote-To-Remote (from serverA to serverB)
      synchronize:
        mode: push
        src: "/tmp/prueba"
        dest: "/tmp"
        rsync_path: "sudo rsync"
      delegate_to: 10.44.36.65
