- name: MIGRACION - Subir archivos
  hosts: all
  tasks:    
    - name: Copy Remote-To-Remote (from serverA to serverB)
      synchronize: src=/test dest=/home/altabox
      delegate_to: 10.44.36.65
