- name: MIGRACION - Subir archivos
  hosts: all
  tasks:    
    - name: Copy Remote-To-Remote (from serverA to serverB)
      synchronize:
        mode: pull
        src: "/tmp/prueba/test3"
        dest: "/tmp"
      delegate_to: 10.44.36.65
