- name: MIGRACION - Preparar
  hosts: all
  tasks:
    - name: Ejecutar scripts de preparar
      shell: wget -O - http://10.44.36.65/migracion/scripts2/000-commons.sh | bash -s '200-preparar.sh'
      become: yes
      
