- name: MIGRACION - Comprobacion
  hosts: all
  tasks:   
    - name: Ejecutar scripts de Comprobacion
      shell: wget -O - http://10.44.36.65/migracion/scripts2/000-commons.sh | bash -s '400-comprobacion.sh'
      become: yes
      
